images:
  tags:
    nodemgr: "10.87.65.243:5000/contrail-nodemgr:5.0.0-139-newton"
    analytics_api: "10.87.65.243:5000/contrail-analytics-api:5.0.0-139-newton"
    contrail_collector: "10.87.65.243:5000/contrail-analytics-collector:5.0.0-139-newton"
    analytics_alarm_gen: "10.87.65.243:5000/contrail-analytics-alarm-gen:5.0.0-139-newton"
    analytics_query_engine: "10.87.65.243:5000/contrail-analytics-query-engine:5.0.0-139-newton"
    analytics_snmp_collector: "10.87.65.243:5000/contrail-analytics-snmp-collector:5.0.0-139-newton"
    contrail_topology: "10.87.65.243:5000/contrail-analytics-topology:5.0.0-139-newton"
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  imagePullPolicy: "IfNotPresent"

labels:
  analytics:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  alarm_gen:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analytics_api:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  contrail_collector:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analytics_nodemgr:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  query_engine:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  snmp_collector:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  contrail_topology:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"


dependencies:
  analytics:
    daemonset:
    - contrail-analyticsdb
  contrail_collector:
    daemonset:
    - contrail-analytics
  alarm_gen:
    daemonset:
    - contrail-analytics
  query_engine:
    daemonset:
    - contrail-analytics
  snmp_collector:
    daemonset:
    - contrail-analytics
  contrail_topology:
    daemonset:
    - contrail-analytics
  analytics_nodemgr:
    daemonset:
    - contrail-analytics

conf:
  # host_os - (OPTIONAL) host operating system release. Sample values "ubuntu" and "centos". Default is ubuntu
  host_os: ubuntu
  controller_nodes: 10.87.65.248
  log_level: SYS_NOTICE

  cloud_orchestrator: openstack
  aaa_mode: cloud-admin

  rabbitmq:
    use_ssl: False

  analytics_zookeeper:
    port: 2181

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  # TO-DO
  cluster_domain: svc.cluster.local
  rabbitmq:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: rabbitmq
        password: password
    path: /
    host: rabbit
    port:
      amqp: 5672
    namespace: openstack
    domain_override: null
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
    host: keystone-api
    namespace: openstack
    path: /v3
    port:
      admin: 35357
      api: 80
    protocol: http

manifests:
  each_container_is_pod: true
  configmap_env: true
  daemonset_analytics: true
