images:
  tags:
    nodemgr: "10.87.65.243:5000/contrail-nodemgr:5.0.0-139-newton"
    contrail_control: "10.87.65.243:5000/contrail-controller-control-control:5.0.0-139-newton"
    control_dns: "10.87.65.243:5000/contrail-controller-control-dns:5.0.0-139-newton"
    control_named: "10.87.65.243:5000/contrail-controller-control-named:5.0.0-139-newton"
    config_api: "10.87.65.243:5000/contrail-controller-config-api:5.0.0-139-newton"
    config_devicemgr: "10.87.65.243:5000/contrail-controller-config-devicemgr:5.0.0-139-newton"
    config_schema_transformer: "10.87.65.243:5000/contrail-controller-config-schema:5.0.0-139-newton"
    config_svcmonitor: "10.87.65.243:5000/contrail-controller-config-svcmonitor:5.0.0-139-newton"
    webui_middleware: "10.87.65.243:5000/contrail-controller-webui-job:5.0.0-139-newton"
    webui: "10.87.65.243:5000/contrail-controller-webui-web:5.0.0-139-newton"
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  imagePullPolicy: "IfNotPresent"

labels:
  controller:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  config_api:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  config_devicemgr:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  schema_transformer:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  svc_monitor:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  config_nodemgr:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  contrail_control:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  control_dns:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  control_named:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  control_nodemgr:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  webui_middleware:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  webui:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"

dependencies:
  config:
    daemonset:
    - contrail-configdb
  schema_transformer:
    daemonset:
    - contrail-config
  svcmonitor:
    daemonset:
    - contrail-config
  devicemgr:
    daemonset:
    - contrail-config
  config_nodemgr:
    daemonset:
    - contrail-config
  control:
    daemonset:
    - contrail-config
  contrail_named:
    daemonset:
    - contrail-control
    - contrail-config
  contrail_dns:
    daemonset:
    - contrail-control
    - contrail-config
  control_nodemgr:
    daemonset:
    - contrail-control
    - contrail-config
  webui:
    daemonset:
    - contrail-config
    - contrail-redis
  webui_middleware:
    daemonset:
    - contrail-config
    - contrail-webui

conf:
  # host_os - (OPTIONAL) host operating system release. Sample values "ubuntu" and "centos". Default is ubuntu
  host_os: ubuntu
  controller_nodes: 10.87.65.248
  log_level: SYS_NOTICE

  cloud_orchestrator: openstack
  aaa_mode: cloud-admin

  rabbitmq:
    use_ssl: False

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  # TO-DO
  cluster_domain: svc.cluster.local
  rabbitmq:
    auth:
      admin:
        username: admin
        password: password
      user:
        username: rabbitmq
        password: password
    path: /
    host: rabbitmq
    port:
      amqp: 5672
    namespace: openstack
    domain_override: null
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
    host: keystone-api
    namespace: openstack
    path: /v3
    port:
      admin: 35357
      api: 80
    protocol: http

manifests:
  each_container_is_pod: true
  configmap_env: true
  daemonset_config: true
  daemonset_control: true
  daemonset_webui: true
  daemonset_agent: true
