images:
  tags:
    nodemgr: "docker.io/opencontrail/contrail-nodemgr:5.0.0-20180220070035-centos7-newton"
    contrail_control: "docker.io/opencontrail/contrail-controller-control-control:5.0.0-20180220070035-centos7-newton"
    control_dns: "docker.io/opencontrail/contrail-controller-control-dns:5.0.0-20180220070035-centos7-newton"
    control_named: "docker.io/opencontrail/contrail-controller-control-named:5.0.0-20180220070035-centos7-newton"
    config_api: "docker.io/opencontrail/contrail-controller-config-api:5.0.0-20180220070035-centos7-newton"
    config_devicemgr: "docker.io/opencontrail/contrail-controller-config-devicemgr:5.0.0-20180220070035-centos7-newton"
    config_schema_transformer: "docker.io/opencontrail/contrail-controller-config-schema:5.0.0-20180220070035-centos7-newton"
    config_svcmonitor: "docker.io/opencontrail/contrail-controller-config-svcmonitor:5.0.0-20180220070035-centos7-newton"
    webui_middleware: "docker.io/opencontrail/contrail-controller-webui-job:5.0.0-20180220070035-centos7-newton"
    webui: "docker.io/opencontrail/contrail-controller-webui-web:5.0.0-20180220070035-centos7-newton"
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  imagePullPolicy: "IfNotPresent"

labels:
  control:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  control_only:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  config:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  webui:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"

dependencies:
  config:
    daemonset:
    - contrail-configdb
  control:
    daemonset:
    - contrail-config
  webui:
    daemonset:
    - contrail-config
    - contrail-redis

contrail_env:
  CONTROLLER_NODES: 10.87.65.248
  LOG_LEVEL: SYS_NOTICE
  CLOUD_ORCHESTRATOR: openstack
  AAA_MODE: cloud-admin


# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  rabbitmq:
    auth:
      username: rabbitmq
      password: password
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5672
    hosts:
      default: rabbitmq
    host_fqdn_override:
       default: null
    domain_override: null
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
      region_name: RegionOne
    hosts:
      default: keystone-api
    path:
      default: /v3
    port:
      admin:
        default: 35357
      api:
        default: 80
    scheme:
      default: http
    host_fqdn_override:
       default: null

# Service related inputs are defined here
service:
  config_api_public_port: ""

manifests:
  configmap_env: true
  daemonset_config: true
  daemonset_control: true
  daemonset_control_only: false
  daemonset_webui: true
  daemonset_agent: true
  service_config_api: true
  service_webui: true
  ingress_webui: true
  ingress_config_api: true
