{{- if and .Values.manifests.each_container_is_pod .Values.manifests.daemonset_analytics }}
{{- $context := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analytics-nodemgr
spec:
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-analytics-nodemgr" | include "contrail-helper.kubernetes_spec.get_metadata_label" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.analytics_nodemgr.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.analytics_nodemgr.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      initContainers:
{{ tuple $context .Values.dependencies.analytics_nodemgr | include "contrail-helper.kubernetes_spec.get_entrypoint_init_container" | indent 8 }}
      containers:
      - name: contrail-analytics-nodemgr
        image: {{ .Values.images.tags.nodemgr | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-analytics
        - configMapRef:
            name: configmap-analytics-auth
        env:
        - name: NODE_TYPE
          value: analytics
        - name: DOCKER_HOST
          value: "unix://mnt/docker.sock"
# todo: there is type Socket in new kubernetes, it is possible to use full
# path:
# hostPath:
#   path: /var/run/docker.sock and
#   type: Socket
        volumeMounts:
        - mountPath: /mnt
          name: docker-unix-socket
        - mountPath: /var/log/contrail/
          name: contrail-log
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run
      - name: contrail-log
        hostPath:
          path: /var/log/contrail/
{{- end }}
