{{- if and .Values.manifests.daemonset_config .Values.manifests.each_container_is_pod }}
{{- $context := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-devicemgr
spec:
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-devicemgr" | include "contrail-helper.kubernetes_spec.get_metadata_label" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.config_devicemgr.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.config_devicemgr.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      initContainers:
{{ tuple $context .Values.dependencies.devicemgr | include "contrail-helper.kubernetes_spec.get_entrypoint_init_container" | indent 8 }}
      containers:
      - name: contrail-devicemgr
        image: {{ .Values.images.tags.config_devicemgr | quote }}
        imagePullPolicy: {{ default "" .Values.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: configmap-controller
        - configMapRef:
            name: configmap-controller-auth
        - configMapRef:
            name: configmap-controller-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
      volumes:
      - name: contrail-log
        hostPath:
          path: /var/log/contrail/
{{- end }}
