{{- if .Values.manifests.ingress_webui }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: contrail-webui
spec:
  rules:
  - host: contrail-webui
    http:
      paths:
      - backend:
          serviceName: contrail-webui
          servicePort: http
        path: /
  - host: contrail-webui.{{ .Release.Namespace }}
    http:
      paths:
      - backend:
          serviceName: contrail-webui
          servicePort: http
        path: /
  - host: contrail-webui.{{ .Release.Namespace }}.svc.cluster.local
    http:
      paths:
      - backend:
          serviceName: contrail-webui
          servicePort: http
        path: /
{{- end }}
